<a href="https://colab.research.google.com/github/Ghan539/Python4DataScientist/blob/main/data_gathering/Session27__API_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import requests

api='48e8ca3ef267a04254b5cf4cde8514ef'

url=f"https://api.themoviedb.org/3/movie/popular?api_key={api}"


resp = requests.get(url)

data = resp.json()

df = pd.DataFrame(data)

df

,page,results,total_pages,total_results
0,1,"{'adult': False, 'backdrop_path': '/qeQJx07rK2...",58800,1175995
1,1,"{'adult': False, 'backdrop_path': '/RMXG8myu1a...",58800,1175995
2,1,"{'adult': False, 'backdrop_path': '/l9mFW9HQnA...",58800,1175995
3,1,"{'adult': False, 'backdrop_path': '/qDa0fqDqIB...",58800,1175995
4,1,"{'adult': False, 'backdrop_path': '/ziXF8wIBgu...",58800,1175995
5,1,"{'adult': False, 'backdrop_path': '/yjK3ardrgd...",58800,1175995
6,1,"{'adult': False, 'backdrop_path': '/hpBGCnzOvd...",58800,1175995
7,1,"{'adult': False, 'backdrop_path': '/4gyx49ibwQ...",58800,1175995
8,1,"{'adult': False, 'backdrop_path': '/rZfmzpixLK...",58800,1175995
9,1,"{'adult': False, 'backdrop_path': '/zFCWfU2ViM...",58800,1175995
10,1,"{'adult': False, 'backdrop_path': '/tK3QdOOrX4...",58800,1175995
11,1,"{'adult': False, 'backdrop_path': '/c4U96GrPRf...",58800,1175995
12,1,"{'adult': False, 'backdrop_path': '/tBZMwg5oCJ...",58800,1175995
13,1,"{'adult': False, 'backdrop_path': '/tBRSSfgqOA...",58800,1175995
14,1,"{'adult': False, 'backdrop_path': '/qjTqY5coNi...",58800,1175995
15,1,"{'adult': False, 'backdrop_path': '/xSJJQeAp9G...",58800,1175995
16,1,"{'adult': False, 'backdrop_path': '/kkcwhgSFd8...",58800,1175995
17,1,"{'adult': False, 'backdrop_path': '/lSd6nEnlae...",58800,1175995
18,1,"{'adult': False, 'backdrop_path': '/z7lZgL5tze...",58800,1175995
19,1,"{'adult': False, 'backdrop_path': '/c6BPbkO5Np...",58800,1175995

In [ ]:
import requests
req=requests.get(f"https://api.themoviedb.org/3/movie/popular?api_key={'48e8ca3ef267a04254b5cf4cde8514ef'}")

data=req.json()


df1=pd.DataFrame(data)
df1.head()

,page,results,total_pages,total_results
0,1,"{'adult': False, 'backdrop_path': '/qeQJx07rK2...",58800,1175995
1,1,"{'adult': False, 'backdrop_path': '/RMXG8myu1a...",58800,1175995
2,1,"{'adult': False, 'backdrop_path': '/l9mFW9HQnA...",58800,1175995
3,1,"{'adult': False, 'backdrop_path': '/qDa0fqDqIB...",58800,1175995
4,1,"{'adult': False, 'backdrop_path': '/ziXF8wIBgu...",58800,1175995

In [ ]:
import requests

rr=requests.get(f"https://api.themoviedb.org/3/movie/popular?api_key={'48e8ca3ef267a04254b5cf4cde8514ef'}")
df2=pd.DataFrame(rr.json())
df2.head()

,page,results,total_pages,total_results
0,1,"{'adult': False, 'backdrop_path': '/qeQJx07rK2...",58800,1175995
1,1,"{'adult': False, 'backdrop_path': '/RMXG8myu1a...",58800,1175995
2,1,"{'adult': False, 'backdrop_path': '/l9mFW9HQnA...",58800,1175995
3,1,"{'adult': False, 'backdrop_path': '/qDa0fqDqIB...",58800,1175995
4,1,"{'adult': False, 'backdrop_path': '/ziXF8wIBgu...",58800,1175995

In [ ]:
# movie list
import requests
api='48e8ca3ef267a04254b5cf4cde8514ef'

url=f'https://api.themoviedb.org/3/genre/movie/list?api_key={api}'

reqq=requests.get(url)
data=reqq.json()

df4=pd.DataFrame(data)
df4

                                    genres
0             {'id': 28, 'name': 'Action'}
1          {'id': 12, 'name': 'Adventure'}
2          {'id': 16, 'name': 'Animation'}
3             {'id': 35, 'name': 'Comedy'}
4              {'id': 80, 'name': 'Crime'}
5        {'id': 99, 'name': 'Documentary'}
6              {'id': 18, 'name': 'Drama'}
7          {'id': 10751, 'name': 'Family'}
8            {'id': 14, 'name': 'Fantasy'}
9            {'id': 36, 'name': 'History'}
10            {'id': 27, 'name': 'Horror'}
11          {'id': 10402, 'name': 'Music'}
12         {'id': 9648, 'name': 'Mystery'}
13        {'id': 10749, 'name': 'Romance'}
14  {'id': 878, 'name': 'Science Fiction'}
15       {'id': 10770, 'name': 'TV Movie'}
16          {'id': 53, 'name': 'Thriller'}
17            {'id': 10752, 'name': 'War'}
18           {'id': 37, 'name': 'Western'}

In [ ]:
import requests
apii='48e8ca3ef267a04254b5cf4cde8514ef'
rq=requests.get(f'https://api.themoviedb.org/3/movie/top_rated?api_key={apii}&language=en-US&page=1')
my_data=rq.json()

df6=pd.DataFrame(my_data['results'])[['id','title','release_date','overview','vote_average','vote_count']]

,id,title,release_date,overview,vote_average,vote_count
0,980431,Avatar Aang: The Last Airbender,2026-07-24,"Avatar Aang, the world's last Airbender, learn...",9.180,1071
1,1632181,Accidental Partners,2026-03-12,Two women discover they were both scammed by t...,8.876,370

In [ ]:
my_df=pd.DataFrame()
my_df

for i in range(1,401):
  rq=requests.get(f'https://api.themoviedb.org/3/movie/top_rated?api_key={apii}&language=en-US&page={i}')
  mydata = rq.json()
  temp_df=pd.DataFrame(mydata['results'])[['id','title','release_date','overview','vote_average','vote_count']]
  my_df = pd.concat([my_df,temp_df],ignore_index=True)

In [ ]:
my_df.to_csv('Gshyam_dataset_api.csv')